sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
gemfile:
  - gemfiles/Gemfile.rails-4-0-stable
  - gemfiles/Gemfile.rails-4-1-stable
  - gemfiles/Gemfile.rails-4-2-stable
  - gemfiles/Gemfile.rails-head
  - Gemfile
exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-head
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile.rails-head
  - rvm: 2.1
    gemfile: gemfiles/Gemfile.rails-head
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "0UzWiVjxtaMsAiLCdK0p5ZIpWi94rmH71hbEQ3tuKTSSrsh9qW16cd39TS6i\nOdlSojcdzACanjIL8Z2qyG2DHScLBZAzWdDNWpnbtpJfDQ+p5ldDdbFmL6+5\n0t2nvv9uNQvhSOMD9ukdb7BFlRvd8Yq7zdjyAKt8efV2Abx7Msk="
